name: autovla_codeclean
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip>=23.3

  - jupyterlab
  - ipykernel
  - notebook

  - numpy=1.23.4

  - pip:
      - -r requirements.txt